branches:
  - main
  - name: beta
    prerelease: true
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: eslint
  - - '@semantic-release/release-notes-generator'
    - preset: eslint
  - - '@semantic-release/npm'
  - - '@semantic-release/github'
    - successComment: "This ${issue.pull_request ? 'pull request is included' : 'issue is resolved'} in version [${nextRelease.version}](<github_release_url>)"
      releasedLabels: ["released<%= nextRelease.channel ? `in ${nextRelease.channel}` : '' %>"]
      assignees:
      - jftanner
      assets:
        - downloads/AmongUsCapture*.exe
