version: '3.5'

services:
  app:
    container_name: sau-bot
    image: ghcr.io/tanndev/silence-among-us:latest
    build: .
    environment:
      - DISCORD_TOKEN
      - HOST
      - PORT
      - SECURE
      - DATABASE_URL=http://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@couch:5984
    ports:
      - 127.0.0.1:8080:8080

  couch:
    container_name: sau-couch
    image: couchdb:3.1
    volumes:
      - couchdb-data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=${DATABASE_USERNAME}
      - COUCHDB_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 127.0.0.1:5984:5984
    expose:
      - 5984

volumes:
  couchdb-data:
