version: '3.5'

services:
  app:
    container_name: sau-bot
    image: ghcr.io/tanndev/silence-among-us:latest
    build: .
    env_file: .env
    environment:
      HOST: localhost
      PORT: 8080
      SECURE: 'false'
    ports:
      - 127.0.0.1:8080:8080

  couch:
    container_name: sau-couch
    image: couchdb:3.1
    volumes:
      - couchdb-data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=sau-bot
      - COUCHDB_PASSWORD=local-development
    ports:
      - 127.0.0.1:5984:5984
    expose:
      - 5984

volumes:
  couchdb-data:
