version: '3.5'

services:
  app:
    container_name: sau-bot
    image: jftanner/silence-among-us
    build: .
    env_file: .env
    environment:
      HOST: localhost
      PORT: 8080
      SECURE: 'false'
    ports:
      - 127.0.0.1:8080:8080

