name: Release
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17.1.2
          extra_plugins: |
            @semantic-release/exec
            conventional-changelog-eslint
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/silence-among-us
          GITHUB_USER: ${{ secrets.RELEASE_GH_USER }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}

      - name: Redeploy Bot
        if: steps.semantic.outputs.new_release_published == 'true' && github.ref == 'refs/heads/main'
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: sau.tanndev.com
          privateKey: ${{ secrets.DEPLOY_SSH_KEY }}
          command: |
            cd /sau
            echo "${{ secrets.DEPLOY_GH_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose pull
            docker-compose up -d
            # TODO Reconfigure the deployment, rather than assuming it's there and working.
